In [1]:
from simplexPL import PL

In [2]:
n = 4
m = 2
pl = PL(n, m)

Digite os elementos do vetor b de custos:
c0: -1
c1: -3
c2: 0
c3: 0


Digite os elementos da matriz A de coeficientes das restrições:
a11: 1
a12: 1
a13: 1
a14: 0


a21: 0
a22: 1
a23: 0
a24: 1


Digite os elementos do vetor b das restrições:
b0: 6
b1: 3


O seu PPL já possui uma base B (igual a identidade 2x2) factível.
[[1. 0.]
 [0. 1.]]


[0. 0. 2. 3.]
[0. 1. 0. 0.]


In [3]:
import numpy as np

In [4]:
xb = np.linalg.solve(pl.B, pl.b)
print(xb)

[6. 3.]


In [5]:
lb = np.linalg.solve(pl.B.transpose(), pl.c[2:4])
print(lb)

[0. 0.]


In [10]:
r = np.zeros(pl.n)
auxn = np.array([0])

for i in range(pl.n):
    if pl.vb[i] == 0:
        r[i] = pl.c[i] - np.dot(lb, pl.A[:, i])
        
print(pl.vn)
print(pl.vb)
print(r)
 
'''    
for i in range(pl.n):
    if pl.vn[i] == 0:
        auxn = np.append(auxn, i)
        
auxn = np.delete(auxn, 0)
r = np.delete(r, auxn)
#pl.vn = np.array([l for l in pl.vn if l == 0])
#pl.vb = np.array([l for l in pl.vb if l == 0])
'''
r = np.array([l for l in r if l != 0])

print(pl.vn)
print(pl.vb)
print(r)
       
if (r >= 0).all():
    print('A solução foi encontrada')
else:
    a = pl.vn[np.argmin(r)]
    print(a)

[0. 1. 0. 0.]
[0. 0. 2. 3.]
[-1. -3.  0.  0.]
[0. 1. 0. 0.]
[0. 0. 2. 3.]
[-1. -3.]
1.0


In [11]:
a = int(a)
d = np.linalg.solve(pl.B, pl.A[:, a])
print(d)

E = np.zeros(pl.m)
for i in range(pl.m):
    if d[i] > 0:
        E[i] = -(xb[i]/d[i])
    else:
        E[i] = 0
        
b = pl.vb[np.argmax(E)]

print(E)
print(b)

[1. 1.]
[-6. -3.]
0.0
