In [1]:
import numpy as np
from simplexPL import PL

In [2]:
n = int(input("Quantas variáveis o problema possui? "))
m = int(input("Quantas restrições o problema possui? "))

Quantas variáveis o problema possui? 6
Quantas restrições o problema possui? 3


In [3]:
pl = PL(n, m)

Digite os elementos do vetor c de custos:
c1: -2
c2: 1
c3: -1
c4: 0
c5: 0
c6: 0


Digite os elementos da matriz A de coeficientes das restrições:
a11: 2
a12: 1
a13: -2
a14: 1
a15: 0
a16: 0


a21: 4
a22: -1
a23: 2
a24: 0
a25: -1
a26: 0


a31: 2
a32: 3
a33: -1
a34: 0
a35: 0
a36: -1


Digite os elementos do vetor b das restrições:
b1: 8
b2: 2
b3: 4


O seu PPL não possui uma base B (igual a identidade 3x3) factível.
Gostaria de usar o método de duas fases[f] ou o BigM[M]? f
f
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[0. 0. 0. 4. 0. 0.]
[1. 2. 3. 0. 5. 6.]


In [4]:
M = pl.I - pl.B
M

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
#M = np.reshape(np.array([M[:,l] for l in range(pl.m) if (M[:, l] != np.zeros((pl.m,1))).any()]),(pl.m, pl.m - pl.C))
M = np.transpose(np.array([M[:,l] for l in range(pl.m) if (M[:, l] != np.zeros((pl.m,1))).any()]))
#pl.B = np.reshape(np.array([pl.B[:,l] for l in range(pl.m) if (pl.B[:, l] != np.zeros((pl.m,1))).any()]),(pl.m, pl.C))
pl.B = np.transpose(np.array([pl.B[:,l] for l in range(pl.m) if (pl.B[:, l] != np.zeros((pl.m,1))).any()]))

In [6]:
print(M)
print(pl.B)

[[0. 0.]
 [1. 0.]
 [0. 1.]]
[[1.]
 [0.]
 [0.]]


In [7]:
pl.B = np.append(pl.B, M, axis=1)
pl.B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
pl.A = np.append(pl.A, M, axis=1)
pl.A

array([[ 2.,  1., -2.,  1.,  0.,  0.,  0.,  0.],
       [ 4., -1.,  2.,  0., -1.,  0.,  1.,  0.],
       [ 2.,  3., -1.,  0.,  0., -1.,  0.,  1.]])

In [9]:
pl.vb = np.append(pl.vb, np.arange(pl.n + 1, pl.n + pl.m - pl.C + 1))
pl.vb

array([0., 0., 0., 4., 0., 0., 7., 8.])

In [10]:
pl.vn = np.append(pl.vn, np.zeros((1, pl.m - pl.C)))
pl.vn

array([1., 2., 3., 0., 5., 6., 0., 0.])

In [11]:
pl.vb = np.array([l for l in pl.vb if l != 0])
for i in range(pl.m):
    if pl.vb[i] >= pl.n + 1 :
        pl.cb[i] = 1
pl.cb

array([0., 1., 1.])

In [12]:
pl.cn = np.append(pl.cn, np.zeros((1, pl.m - pl.C)))
pl.cn

array([0., 0., 0., 0., 0.])

In [13]:
pl.vn = np.array([l for l in pl.vn if l != 0])
for i in range(pl.n - pl.C):
    pl.cn[i] = pl.c[int(pl.vn[i])-1]
pl.cn

array([-2.,  1., -1.,  0.,  0.])

In [14]:
pl.r = np.append(pl.r, np.zeros((1, pl.m - pl.C)))
pl.r

array([0., 0., 0., 0., 0.])

In [15]:
pl.o = pl.n - pl.C
pl.o

5

In [16]:
pl.c = np.append(pl.c, np.ones((1, pl.m - pl.C)))
pl.c

array([-2.,  1., -1.,  0.,  0.,  0.,  1.,  1.])

In [17]:
pl.Simplex()

Iteração: 1
xb = [8. 2. 4.]
lb = [0. 1. 1.]
r = [-8. -1. -2.  1.  1.]
Variável que entra : 1.0
direção = [2. 4. 2.]
passo = [4.  0.5 2. ]
Variável que sai: 7.0
vb = [4. 1. 8.]
cb = [ 0. -2.  1.]
vn = [7. 2. 3. 5. 6.]
cn = [ 1.  1. -1.  0.  0.]
B = [[1. 2. 0.]
 [0. 4. 0.]
 [0. 2. 1.]]


Iteração: 2
xb = [7.  0.5 3. ]
lb = [ 0. -1.  1.]
r = [ 2. -3.  2. -1.  1.]
Variável que entra : 2.0
direção = [ 1.5  -0.25  3.5 ]
passo = [4.66666667e+00 1.09663316e+03 8.57142857e-01]
Variável que sai: 8.0
vb = [4. 1. 2.]
cb = [ 0. -2.  1.]
vn = [7. 8. 3. 5. 6.]
cn = [ 1.  1. -1.  0.  0.]
B = [[ 1.  2.  1.]
 [ 0.  4. -1.]
 [ 0.  2.  3.]]


Iteração: 3
xb = [5.71428571 0.71428571 0.85714286]
lb = [ 2.22044605e-16 -5.71428571e-01  1.42857143e-01]
r = [ 1.57142857  0.85714286  0.28571429 -0.57142857  0.14285714]
Variável que entra : 5.0
direção = [ 0.28571429 -0.21428571  0.14285714]
passo = [ 20.         303.16757768   6.        ]
Variável que sai: 2.0
vb = [4. 1. 5.]
cb = [ 0. -2.  0.]
vn = [7. 8. 3. 2.